project:
  type: website

website:
  title: "R & K-디아스포라 워크샵"
  navbar:
    left:
      - href: index.qmd
        text: "홈"
      - 1_prerequisite.qmd
      - 5_basic.qmd
      - 2_tidytext.qmd
      - 3_tidygraph.qmd
      - 4_shiny.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

